export const data = [
  {
    id: "1",
    1: "John",
    2: 24,
    3: "john@cemento.com",
    4: true,
    5: ["R&D", "Sales", "Finance", "Administration"],
  },
  {
    id: "2",
    1: "Alice",
    2: 30,
    3: "alice@cemento.com",
    4: false,
    5: ["Sales", "Marketing", "Human Resources"],
  },
  {
    id: "3",
    1: "Bob",
    2: 28,
    3: "bob@cemento.com",
    4: true,
    5: ["R&D", "Finance", "Administration"],
  },
  {
    id: "4",
    1: "Eva",
    2: 35,
    3: "eva@cemento.com",
    4: false,
    5: ["Marketing", "Human Resources"],
  },
  {
    id: "5",
    1: "Charlie",
    2: 32,
    3: "charlie@cemento.com",
    4: true,
    5: ["R&D", "Administration"],
  },
  {
    id: "6",
    1: "Grace",
    2: 27,
    3: "grace@cemento.com",
    4: true,
    5: ["Sales", "Finance"],
  },
  {
    id: "7",
    1: "David",
    2: 29,
    3: "david@cemento.com",
    4: false,
    5: ["R&D", "Marketing", "Administration"],
  },
  {
    id: "8",
    1: "Sophie",
    2: 26,
    3: "sophie@cemento.com",
    4: true,
    5: ["Sales", "Finance", "Human Resources"],
  },
  {
    id: "9",
    1: "Frank",
    2: 33,
    3: "frank@cemento.com",
    4: false,
    5: ["Marketing"],
  },
  {
    id: "10",
    1: "Hannah",
    2: 31,
    3: "hannah@cemento.com",
    4: true,
    5: ["R&D", "Sales", "Finance", "Administration"],
  },
  {
    id: "11",
    1: "Oliver",
    2: 34,
    3: "oliver@cemento.com",
    4: true,
    5: ["R&D", "Finance"],
  },
  {
    id: "12",
    1: "Emma",
    2: 25,
    3: "emma@cemento.com",
    4: false,
    5: ["Sales", "Human Resources"],
  },
  {
    id: "13",
    1: "Liam",
    2: 29,
    3: "liam@cemento.com",
    4: true,
    5: ["R&D", "Sales", "Finance"],
  },
  {
    id: "14",
    1: "Mia",
    2: 28,
    3: "mia@cemento.com",
    4: false,
    5: ["Marketing", "Administration"],
  },
  {
    id: "15",
    1: "Caleb",
    2: 26,
    3: "caleb@cemento.com",
    4: true,
    5: ["Sales", "Finance", "Human Resources"],
  },
  {
    id: "16",
    1: "Isabella",
    2: 33,
    3: "isabella@cemento.com",
    4: false,
    5: ["Marketing"],
  },
  {
    id: "17",
    1: "Jackson",
    2: 31,
    3: "jackson@cemento.com",
    4: true,
    5: ["R&D", "Sales", "Finance", "Administration"],
  },
  {
    id: "18",
    1: "Sophia",
    2: 30,
    3: "sophia@cemento.com",
    4: true,
    5: ["R&D", "Finance"],
  },
  {
    id: "19",
    1: "Ethan",
    2: 27,
    3: "ethan@cemento.com",
    4: false,
    5: ["Sales", "Marketing", "Human Resources"],
  },
  {
    id: "20",
    1: "Ava",
    2: 29,
    3: "ava@cemento.com",
    4: true,
    5: ["R&D", "Administration"],
  },
  {
    id: "21",
    1: "Noah",
    2: 26,
    3: "noah@cemento.com",
    4: true,
    5: ["Sales", "Finance"],
  },
  {
    id: "22",
    1: "Madison",
    2: 32,
    3: "madison@cemento.com",
    4: false,
    5: ["R&D", "Marketing", "Administration"],
  },
  {
    id: "23",
    1: "Liam",
    2: 28,
    3: "liam@cemento.com",
    4: true,
    5: ["R&D", "Finance", "Administration"],
  },
  {
    id: "24",
    1: "Zoe",
    2: 35,
    3: "zoe@cemento.com",
    4: false,
    5: ["Marketing", "Human Resources"],
  },
  {
    id: "25",
    1: "Lucas",
    2: 31,
    3: "lucas@cemento.com",
    4: true,
    5: ["Sales", "Finance", "Human Resources"],
  },
  {
    id: "26",
    1: "Aria",
    2: 33,
    3: "aria@cemento.com",
    4: false,
    5: ["Marketing"],
  },
  {
    id: "27",
    1: "Logan",
    2: 30,
    3: "logan@cemento.com",
    4: true,
    5: ["R&D", "Sales", "Finance", "Administration"],
  },
  {
    id: "28",
    1: "Emma",
    2: 29,
    3: "emma@cemento.com",
    4: true,
    5: ["R&D", "Finance"],
  },
  {
    id: "29",
    1: "Mason",
    2: 27,
    3: "mason@cemento.com",
    4: false,
    5: ["Sales", "Human Resources"],
  },
  {
    id: "30",
    1: "Sophie",
    2: 34,
    3: "sophie@cemento.com",
    4: true,
    5: ["Marketing"],
  },
  {
    id: "31",
    1: "Carter",
    2: 31,
    3: "carter@cemento.com",
    4: false,
    5: ["R&D", "Sales", "Finance", "Administration"],
  },
  {
    id: "32",
    1: "Abigail",
    2: 28,
    3: "abigail@cemento.com",
    4: true,
    5: ["R&D", "Finance"],
  },
  {
    id: "33",
    1: "Elijah",
    2: 26,
    3: "elijah@cemento.com",
    4: true,
    5: ["Sales", "Marketing", "Human Resources"],
  },
  {
    id: "34",
    1: "Harper",
    2: 29,
    3: "harper@cemento.com",
    4: false,
    5: ["R&D", "Administration"],
  },
  {
    id: "35",
    1: "Alexander",
    2: 27,
    3: "alexander@cemento.com",
    4: true,
    5: ["Sales", "Finance"],
  },
  {
    id: "36",
    1: "Avery",
    2: 32,
    3: "avery@cemento.com",
    4: false,
    5: ["R&D", "Marketing", "Administration"],
  },
  {
    id: "37",
    1: "William",
    2: 28,
    3: "william@cemento.com",
    4: true,
    5: ["R&D", "Finance", "Administration"],
  },
  {
    id: "38",
    1: "Lily",
    2: 35,
    3: "lily@cemento.com",
    4: true,
    5: ["Marketing", "Human Resources"],
  },
  {
    id: "39",
    1: "Owen",
    2: 31,
    3: "owen@cemento.com",
    4: false,
    5: ["Sales", "Finance", "Human Resources"],
  },
  {
    id: "40",
    1: "Aria",
    2: 33,
    3: "aria@cemento.com",
    4: false,
    5: ["Marketing"],
  },
];

export const columns = [
  { id: "1", ordinalNo: 2, title: "Name", type: "string" },
  { id: "2", ordinalNo: 1, title: "Age", type: "number" },
  { id: "3", ordinalNo: 3, title: "Email", type: "string", width: 300 },
  { id: "4", ordinalNo: 4, title: "Active", type: "boolean" },
  { id: "5", ordinalNo: 5, title: "Department", type: "selection" },
];

export const tableData = {
  data,
  columns,
};
